### ISSUE TITLE
Ubuntu 12.04 pkg_resources.DistributionNotFound: pep8-naming

### ISSUE THREAD

**Issue by weldpua2008** [PyCQA/prospector#123]
Hi have the same error:
https://github.com/landscapeio/prospector/issues/110

``` bash
#prospector
-bash: prospector: command not found
root@RDE-1.3:/home.local/valerys/rde_1_3/rdepyui# pip install prospector
Collecting prospector
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading prospector-0.10.2.tar.gz
Collecting pylint>=1.4 (from prospector)
  Downloading pylint-1.4.3-py2.py3-none-any.whl (428kB)
    100% |████████████████████████████████| 430kB 111kB/s
Collecting pylint-celery>=0.3 (from prospector)
  Downloading pylint-celery-0.3.tar.gz
Collecting pylint-django>=0.6 (from prospector)
  Downloading pylint-django-0.6.tar.gz
Collecting pylint-plugin-utils>=0.2.3 (from prospector)
  Downloading pylint-plugin-utils-0.2.3.tar.gz
Collecting pylint-common>=0.2.1 (from prospector)
  Downloading pylint-common-0.2.1.tar.gz
Collecting requirements-detector>=0.4 (from prospector)
  Downloading requirements-detector-0.4.tar.gz
Collecting setoptconf>=0.2.0 (from prospector)
  Downloading setoptconf-0.2.0.tar.gz
Collecting dodgy>=0.1.7 (from prospector)
  Downloading dodgy-0.1.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python2.7/dist-packages (from prospector)
Collecting mccabe>=0.2.1 (from prospector)
  Downloading mccabe-0.3-py2.py3-none-any.whl
Collecting pyflakes>=0.8.1 (from prospector)
  Downloading pyflakes-0.8.1-py2.py3-none-any.whl
Collecting pep8>=1.6.0 (from prospector)
  Downloading pep8-1.6.2-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 182kB/s
Collecting pep8-naming>=0.2.2 (from prospector)
  Downloading pep8_naming-0.2.2-py2.py3-none-any.whl
Collecting pep257>=0.3.2 (from prospector)
  Downloading pep257-0.5.0.tar.gz
Collecting logilab-common>=0.53.0 (from pylint>=1.4->prospector)
  Downloading logilab-common-0.63.2.tar.gz (196kB)
    100% |████████████████████████████████| 200kB 79kB/s
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pylint>=1.4->prospector)
Collecting astroid>=1.3.6 (from pylint>=1.4->prospector)
  Downloading astroid-1.3.6-py2.py3-none-any.whl (182kB)
    100% |████████████████████████████████| 184kB 83kB/s
Installing collected packages: logilab-common, astroid, pylint, pylint-plugin-utils, pylint-celery, pylint-django, pylint-common, requirements-detector, setoptconf, dodgy, mccabe, pyflakes, pep8, pep8-naming, pep257, prospector
  Running setup.py install for logilab-common
  Running setup.py install for pylint-plugin-utils
  Running setup.py install for pylint-celery
  Running setup.py install for pylint-django
  Running setup.py install for pylint-common
  Running setup.py install for requirements-detector
  Running setup.py install for setoptconf
  Running setup.py install for dodgy
  Running setup.py install for pep257
  Running setup.py install for prospector
Successfully installed astroid-1.3.6 dodgy-0.1.7 logilab-common-0.63.2 mccabe-0.3 pep257-0.5.0 pep8-1.6.2 pep8-naming-0.2.2 prospector-0.10.2 pyflakes-0.8.1 pylint-1.4.3 pylint-celery-0.3 pylint-common-0.2.1 pylint-django-0.6 pylint-plugin-utils-0.2.3 requirements-detector-0.4 setoptconf-0.2.0
root@RDE-1.3:/home.local/valerys/rde_1_3/rdepyui# prospector
Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pep8-naming>=0.2.2
```

**Comment by weldpua2008** [comment]
I fixed this:
# easy_install --upgrade pip
Searching for pip
Reading http://pypi.python.org/simple/pip/
Best match: pip 6.1.1
Downloading https://pypi.python.org/packages/source/p/pip/pip-6.1.1.tar.gz#md5=6b19e0a934d982a5a4b798e957cb6d45
Processing pip-6.1.1.tar.gz
Running pip-6.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-VTJWjQ/pip-6.1.1/egg-dist-tmp-EyKP64
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 6.1.1 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pip-6.1.1-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
root@RDE-1.3:/home.local/valerys/rde_1_3/rdepyui# easy_install --upgrade prospector
Searching for prospector
Reading http://pypi.python.org/simple/prospector/
Best match: prospector 0.10.2
Downloading https://pypi.python.org/packages/source/p/prospector/prospector-0.10.2.tar.gz#md5=ce992d535ecb240bca23885f5171b850
Processing prospector-0.10.2.tar.gz
Running prospector-0.10.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kjp2GX/prospector-0.10.2/egg-dist-tmp-hjPIST
Adding prospector 0.10.2 to easy-install.pth file
Installing prospector script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/prospector-0.10.2-py2.7.egg
Processing dependencies for prospector
Searching for pep8-naming>=0.2.2
Reading http://pypi.python.org/simple/pep8-naming/
Best match: pep8-naming 0.2.2
Downloading https://pypi.python.org/packages/source/p/pep8-naming/pep8-naming-0.2.2.tar.gz#md5=feb6f2e48889cc18499ec263b2bee468
Processing pep8-naming-0.2.2.tar.gz
Running pep8-naming-0.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-I3D5Ka/pep8-naming-0.2.2/egg-dist-tmp-gfczcM
Adding pep8-naming 0.2.2 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pep8_naming-0.2.2-py2.7.egg
Searching for pep8>=1.6.0
Reading http://pypi.python.org/simple/pep8/
Best match: pep8 1.6.2
Downloading https://pypi.python.org/packages/source/p/pep8/pep8-1.6.2.tar.gz#md5=c7a3f57d832484a6295164661fbb1335
Processing pep8-1.6.2.tar.gz
Running pep8-1.6.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-LZJmR7/pep8-1.6.2/egg-dist-tmp-DOvNRl
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'testsuite'
warning: no previously-included files matching '*.pyo' found under directory 'testsuite'
no previously-included directories found matching 'docs/_build'
Adding pep8 1.6.2 to easy-install.pth file
Installing pep8 script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pep8-1.6.2-py2.7.egg
Searching for pyflakes>=0.8.1
Reading http://pypi.python.org/simple/pyflakes/
Best match: pyflakes 0.8.1
Downloading https://pypi.python.org/packages/source/p/pyflakes/pyflakes-0.8.1.tar.gz#md5=905fe91ad14b912807e8fdc2ac2e2c23
Processing pyflakes-0.8.1.tar.gz
Running pyflakes-0.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1xDeXf/pyflakes-0.8.1/egg-dist-tmp-YchYBy
zip_safe flag not set; analyzing archive contents...
pyflakes.checker: module references __file__
pyflakes.checker: module references __path__
pyflakes.test.test_undefined_names: module references __file__
pyflakes.test.test_undefined_names: module references __path__
pyflakes.test.test_api: module references __file__
Adding pyflakes 0.8.1 to easy-install.pth file
Installing pyflakes script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pyflakes-0.8.1-py2.7.egg
Searching for mccabe>=0.2.1
Reading http://pypi.python.org/simple/mccabe/
Best match: mccabe 0.3
Downloading https://pypi.python.org/packages/source/m/mccabe/mccabe-0.3.tar.gz#md5=81640948ff226f8c12b3277059489157
Processing mccabe-0.3.tar.gz
Running mccabe-0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Oscosa/mccabe-0.3/egg-dist-tmp-VjUCt_
Adding mccabe 0.3 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/mccabe-0.3-py2.7.egg
Searching for pylint>=1.4
Reading http://pypi.python.org/simple/pylint/
Best match: pylint 1.4.3
Downloading https://pypi.python.org/packages/source/p/pylint/pylint-1.4.3.tar.gz#md5=5924c1c7ca5ca23647812f5971d0ea44
Processing pylint-1.4.3.tar.gz
Running pylint-1.4.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Dd4zSc/pylint-1.4.3/egg-dist-tmp-fM0HBi
warning: no files found matching '*.html' under directory 'doc'
zip_safe flag not set; analyzing archive contents...
pylint.epylint: module references __file__
pylint.reporters.__init__: module references __path__
pylint.checkers.__init__: module references __path__
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/raising_non_exception_py3.py', 13, 14, 'raise Exc from missing # [raising-non-exception]\n'))

SyntaxError: ("'yield' outside function", ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/yield_outside_func.py', 2, None, 'yield 1  # [yield-outside-function]\n'))

SyntaxError: ('unknown encoding: IBO-8859-1', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/unknown_encoding_py30.py', 0, 0, None))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/unbalanced_tuple_unpacking_py30.py', 9, 20, '    first, second, *last = (1, 2, 3, 4)\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/abstract_class_instantiated_py3.py', 14, 34, 'class GoodClass(object, metaclass=abc.ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/undefined_variable_py30.py', 8, 19, '    def test(self)->Undefined: # [undefined-variable]\n'))

SyntaxError: ('unknown encoding: IBO-8859-1', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/unknown_encoding_py29.py', 0, 0, None))

SyntaxError: ('unknown encoding: IBO-8859-1', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/unknown_encoding_pypy.py', 0, 0, None))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/class_members_py30.py', 34, 38, 'class TestMetaclass(object, metaclass=ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/functional/abstract_method_py3.py', 35, 34, 'class Structure(object, metaclass=abc.ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_noerror_unused_variable_py30.py', 12, 21, '        nonlocal attr\n'))

SyntaxError: ('keyword argument repeated', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_keyword_repeat.py', 8, None, 'function_default_arg(two=5, two=7)\n'))

/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_assert_2uple.py:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, 2 == 2), "no error"
/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_assert_2uple.py:5: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, 2 == 2) #this should generate a warning
/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_assert_2uple.py:7: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, ), "no error"
/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_assert_2uple.py:8: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, )
/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_assert_2uple.py:9: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (1 == 1, 2 == 2, 3 == 5), "no error"
/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_assert_2uple.py:11: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (True, 'error msg') #this should generate a warning
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_used_before_assignment_py30.py', 10, 20, '        nonlocal cnt\n'))

SyntaxError: ("'return' outside function", ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_return_outside_func.py', 3, None, 'return\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_kwoa_py30.py', 3, 15, 'def function(*, foo):\n'))

SyntaxError: ("duplicate argument '_' in function definition",)

SyntaxError: ('from __future__ imports must occur at the beginning of the file', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_3k_removed_stuff_py_30.py', 4, None, 'from __future__ import generators, print_function\n'))

SyntaxError: ("default 'except:' must be last", ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_w0705.py', 28, None, '__revision__ += 1\n'))

Sorry: IndentationError: ('expected an indented block', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/syntax_error.py', 2, 5, "print('hop')\n"))
SyntaxError: ("'continue' not properly in loop", ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_continue_not_in_loop.py', 8, None, 'continue\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_unused_import_py30.py', 10, 21, 'class Meta(metaclass=abc.ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_syntax_error.py', 1, 9, 'def toto\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_undefined_metaclass_var_py30.py', 8, 20, 'class Bad(metaclass=ABCMet):\n'))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_exec_used_py30.py', 6, 22, "exec('a = 1', globals={})\n"))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg/pylint/test/input/func_bad_exception_context_py30.py', 14, 25, '    raise IndexError from 1\n'))

SyntaxError: ("'return' with argument inside generator",)

Adding pylint 1.4.3 to easy-install.pth file
Installing epylint script to /usr/local/bin
Installing pylint-gui script to /usr/local/bin
Installing pylint script to /usr/local/bin
Installing symilar script to /usr/local/bin
Installing pyreverse script to /usr/local/bin
Installing pylint script to /usr/local/bin
Installing epylint script to /usr/local/bin
Installing pyreverse script to /usr/local/bin
Installing pylint-gui script to /usr/local/bin
Installing symilar script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pylint-1.4.3-py2.7.egg
Searching for astroid>=1.0.0
Reading http://pypi.python.org/simple/astroid/
Best match: astroid 1.3.6
Downloading https://pypi.python.org/packages/source/a/astroid/astroid-1.3.6.tar.gz#md5=0d387f5b2e878f424b95af3bfe44e106
Processing astroid-1.3.6.tar.gz
Running astroid-1.3.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-D83hjL/astroid-1.3.6/egg-dist-tmp-KccfG9
zip_safe flag not set; analyzing archive contents...
astroid.modutils: module references __file__
astroid.modutils: module references __path__
astroid.manager: module references __file__
astroid.raw_building: module references __file__
astroid.raw_building: module references __path__
astroid.builder: module references __file__
astroid.__init__: module references __file__
astroid.scoped_nodes: module references __file__
astroid.scoped_nodes: module references __path__
astroid.tests.unittest_inference: module references __file__
astroid.tests.unittest_scoped_nodes: module references __file__
astroid.tests.unittest_scoped_nodes: module references __path__
astroid.tests.unittest_regrtest: module references __file__
astroid.tests.unittest_modutils: module references __file__
astroid.tests.unittest_modutils: module references __path__
astroid.tests.unittest_lookup: module references __path__
astroid.tests.unittest_manager: module references __file__
astroid.tests.unittest_utils: module references __file__
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/astroid-1.3.6-py2.7.egg/astroid/tests/testdata/python3/data/module2.py', 100, 22, "print('bonjour', file=stream)\n"))

SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/astroid-1.3.6-py2.7.egg/astroid/tests/testdata/python3/data/module.py', 55, 32, "                print('yo', end=' ')\n"))

Adding astroid 1.3.6 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/astroid-1.3.6-py2.7.egg
Searching for six
Reading http://pypi.python.org/simple/six/
Best match: six 1.9.0
Downloading https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz#md5=476881ef4012262dfc8adc645ee786c4
Processing six-1.9.0.tar.gz
Running six-1.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-AtHCKv/six-1.9.0/egg-dist-tmp-aBc0jS
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
six: module references __path__
Adding six 1.9.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/six-1.9.0-py2.7.egg
Finished processing dependencies for prospector
