### ISSUE TITLE
periodically fail bug

### ISSUE THREAD

**Issue by pahaz** [PyCQA/prospector#173]
We use prospector on CI. And periodically prospector fail with this error: 

```
prospector --profile .prospector.yaml --die-on-tool-error
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-3.5.1/bin/prospector", line 9, in <module>
    load_entry_point('prospector==0.11.7', 'console_scripts', 'prospector')()
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/prospector/run.py", line 159, in main
    prospector.execute()
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/prospector/run.py", line 65, in execute
    messages += tool.run(found_files)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/prospector/tools/pylint/__init__.py", line 232, in run
    self._linter.check(self._args)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/lint.py", line 736, in check
    self._do_check(files_or_modules)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/lint.py", line 867, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/lint.py", line 947, in check_astroid_module
    walker.walk(ast_node)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/utils.py", line 935, in walk
    cb(astroid)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/pylint/checkers/classes.py", line 588, in visit_attribute
    self._accessed[-1][attrname].append(node)
IndexError: list index out of range

prospector --profile .prospector.yaml --die-on-tool-error returned exit code 1
```

rebuild without cache solve this problem. But it`s **little annoying**.

**Comment by carlio** [comment]
Could you try again with new prospector/pylint/astroid releases in the last few weeks? Might have been fixed by accident.
