### ISSUE TITLE
Tool vulture failed to run (exception was raised)

### ISSUE THREAD

**Issue by smspillaz** [PyCQA/prospector#180]
The relevant exception is:

```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    include_package_data=True)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/smspillaz/.envirius/envs/python3/lib/python3.5/site-packages/polysquare_setuptools_lint/__init__.py", line 622, in run
    mapper):
  File "/home/smspillaz/.envirius/envs/python3/lib/python3.5/site-packages/polysquare_setuptools_lint/__init__.py", line 561, in _map_over_linters
    self.disable_linters)])
  File "/home/smspillaz/.envirius/envs/python3/lib/python3.5/site-packages/polysquare_setuptools_lint/__init__.py", line 83, in _stamped_deps
    return jobstamp.run(func, dependencies, *args, **kwargs)
  File "/home/smspillaz/.envirius/envs/python3/lib/python3.5/site-packages/jobstamps/jobstamp.py", line 220, in run
    return func(*args, **detail.kwargs)
  File "/home/smspillaz/.envirius/envs/python3/lib/python3.5/site-packages/polysquare_setuptools_lint/__init__.py", line 204, in _run_prospector_on
    prospector.execute()
  File "/home/smspillaz/.envirius/envs/python3/lib/python3.5/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "/home/smspillaz/.envirius/envs/python3/lib/python3.5/site-packages/prospector/tools/vulture/__init__.py", line 67, in run
    for message in vulture.get_messages()
  File "/home/smspillaz/.envirius/envs/python3/lib/python3.5/site-packages/prospector/tools/vulture/__init__.py", line 46, in get_messages
    loc = Location(item.file, None, None, item.lineno, -1)
AttributeError: 'Item' object has no attribute 'file'
```

The reason this is happening is that vulture's internal API appears to have changed and we support vulture versions >= 0.6

**Comment by smspillaz** [comment]
Bump? This bug is pretty annoying and I have a PR open for it.

**Comment by carlio** [comment]
Closed as PR was merged
