### ISSUE TITLE
When specifiying a single file to inspect, prospector search local folder ?

### ISSUE THREAD

**Issue by nMustaki** [PyCQA/prospector#187]
Hello,

first thanks for prospector !
I am trying to lint a file which is **not** in the local directory:

``` shell
/home/nathan/dev/envs/project/bin/prospector /home/nathan/dev/project/notification/mail_data.py
```

If I run the command in the folder containing the file (eg /home/nathan/dev/project/notification/), it works ok, but if I run the command from my home, prospector will fail after some time with permissions errors from directories it shouldn't touch:

``` shell
Traceback (most recent call last):
  File "/home/nathan/dev/envs/project/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/home/nathan/dev/envs/project/local/lib/python2.7/site-packages/prospector/run.py", line 154, in main
    config = ProspectorConfig()
  File "/home/nathan/dev/envs/project/local/lib/python2.7/site-packages/prospector/config/__init__.py", line 34, in __init__
    self.libraries = self._find_used_libraries(self.config, self.profile)
  File "/home/nathan/dev/envs/project/local/lib/python2.7/site-packages/prospector/config/__init__.py", line 169, in _find_used_libraries
    map(libraries.append, autodetect_libraries(self.workdir))
  File "/home/nathan/dev/envs/project/local/lib/python2.7/site-packages/prospector/autodetect.py", line 94, in autodetect_libraries
    libraries = find_from_path(path)
  File "/home/nathan/dev/envs/project/local/lib/python2.7/site-packages/prospector/autodetect.py", line 51, in find_from_path
    names |= find_from_path(item_path)
  File "/home/nathan/dev/envs/project/local/lib/python2.7/site-packages/prospector/autodetect.py", line 51, in find_from_path
    names |= find_from_path(item_path)
  File "/home/nathan/dev/envs/project/local/lib/python2.7/site-packages/prospector/autodetect.py", line 46, in find_from_path
    for item in os.listdir(path):
OSError: [Errno 13] Permission denied: '/home/nathan/.cache/dconf'
```

My guess is that it is scanning recursively local directories from the current path, but in my case that's a wrong assumption.

**Comment by carlio** [comment]
This seems to at least work for me now so I will close this, reopen if it is still happening for you.

**Comment by nMustaki** [comment]
Seems ok now thanks
