### ISSUE TITLE
pylint crashes when called via prospector

### ISSUE THREAD

**Issue by jabdoa2** [PyCQA/prospector#209]
Pylint works when calling it directy but crashes when called via prospector:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/astroid/manager.py", line 129, in ast_from_module_name
    module = modutils.load_module_from_name(modname)
  File "/usr/local/lib/python3.4/dist-packages/astroid/modutils.py", line 190, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/usr/local/lib/python3.4/dist-packages/astroid/modutils.py", line 232, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'pinproc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 11, in <module>
    load_entry_point('prospector==0.12.5', 'console_scripts', 'prospector')()
  File "/usr/local/lib/python3.4/dist-packages/prospector/run.py", line 165, in main
    prospector.execute()
  File "/usr/local/lib/python3.4/dist-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "/usr/local/lib/python3.4/dist-packages/prospector/tools/pylint/__init__.py", line 232, in run
    self._linter.check(self._args)
  File "/usr/local/lib/python3.4/dist-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python3.4/dist-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python3.4/dist-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.4/dist-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/usr/local/lib/python3.4/dist-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/usr/local/lib/python3.4/dist-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/usr/local/lib/python3.4/dist-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/usr/local/lib/python3.4/dist-packages/pylint/checkers/typecheck.py", line 721, in visit_assign
    function_node = safe_infer(node.value.func)
  File "/usr/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/pylint/checkers/utils.py", line 777, in safe_infer
    next(inferit)
  File "/usr/local/lib/python3.4/dist-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/usr/local/lib/python3.4/dist-packages/astroid/decorators.py", line 138, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.4/dist-packages/astroid/inference.py", line 237, in infer_attribute
    for owner in self.expr.infer(context):
  File "/usr/local/lib/python3.4/dist-packages/astroid/context.py", line 40, in cache_generator
    for result in generator:
  File "/usr/local/lib/python3.4/dist-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/usr/local/lib/python3.4/dist-packages/astroid/bases.py", line 95, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/usr/local/lib/python3.4/dist-packages/astroid/context.py", line 40, in cache_generator
    for result in generator:
  File "/usr/local/lib/python3.4/dist-packages/astroid/decorators.py", line 82, in wrapped
    generator = _func(node, context, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/astroid/inference.py", line 226, in infer_import_from
    stmts = module.getattr(name, ignore_locals=module is self.root())
  File "/usr/local/lib/python3.4/dist-packages/astroid/scoped_nodes.py", line 345, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "/usr/local/lib/python3.4/dist-packages/astroid/scoped_nodes.py", line 409, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/usr/local/lib/python3.4/dist-packages/astroid/manager.py", line 133, in ast_from_module_name
    modname=modname, path=spec.location, error=ex))
AttributeError: 'module' object has no attribute 'location'
```

pinproc is a library which is imported in a try block because not everybody has it (e.g. I did not install it on my notebook). This should not crash in my opinion.

**Comment by chocoelho** [comment]
Closing this issue because it's related to an old prospector version.
