### ISSUE TITLE
prospector crashes on startup if a recent pyroma is installed

### ISSUE THREAD

**Issue by njsmith** [PyCQA/prospector#229]
If I install `pyroma==2.0`, then prospector works fine.

But pyroma 2.1 was released ~a year ago, and it removed the attribute `pyroma.ratings.PEP386Version`, which `prospector` unconditionally references during startup (if pyroma is installed). If I have `pyroma==2.1` or `pyroma==2.2`, then I get:

```
$ prospector --help
Traceback (most recent call last):
  File "/home/njs/.user-python3.5-64bit/bin/prospector", line 7, in <module>
    from prospector.run import main
  File "/home/njs/.user-python3.5-64bit/local/lib/python3.5/site-packages/prospector/run.py", line 8, in <module>
    from prospector import blender, postfilter, tools
  File "/home/njs/.user-python3.5-64bit/local/lib/python3.5/site-packages/prospector/tools/__init__.py", line 48, in <module>
    'pyroma': _optional_tool('pyroma'),
  File "/home/njs/.user-python3.5-64bit/local/lib/python3.5/site-packages/prospector/tools/__init__.py", line 29, in _optional_tool
    tool_package = __import__(package_name, fromlist=[tool_class_name])
  File "/home/njs/.user-python3.5-64bit/local/lib/python3.5/site-packages/prospector/tools/pyroma/__init__.py", line 27, in <module>
    ratings.PEP386Version: 'PYR04',
AttributeError: module 'pyroma.ratings' has no attribute 'PEP386Version'
```

Note that it doesn't matter whether prospector has pyroma *enabled* -- if you have pyroma and prospector in the same venv, then prospector doesn't work at all.

**Comment by chocoelho** [comment]
Prospector now uses the latest pyroma version. It'll be integrated into version 0.12.9. Closing this issue since it's fixed.
