### ISSUE TITLE
Fail to run with latest Vulture 0.25

### ISSUE THREAD

**Issue by volans-** [PyCQA/prospector#230]
Installing `prospector[with_everything]` brings the latest Vulture (0.25) that has changed the signature of the `Vulture()` class constructor recently hence failing with:

```
Traceback (most recent call last):
  File ".tox/prospector/bin/prospector", line 11, in <module>
    sys.exit(main())
  File ".tox/prospector/lib/python2.7/site-packages/prospector/run.py", line 165, in main
    prospector.execute()
  File ".tox/prospector/lib/python2.7/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File ".tox/prospector/lib/python2.7/site-packages/prospector/tools/vulture/__init__.py", line 69, in run
    vulture = ProspectorVulture(found_files)
  File ".tox/prospector/lib/python2.7/site-packages/prospector/tools/vulture/__init__.py", line 11, in __init__
    Vulture.__init__(self, exclude=None, verbose=False)
TypeError: __init__() got an unexpected keyword argument 'exclude'
```

See https://github.com/jendrikseipp/vulture/commit/d35e73dedaf26c4f4b693760e168a87ef7b72579 and nearby commits.

It seems to me that the vulture dependency in https://github.com/landscapeio/prospector/blob/master/setup.py#L62 should have an upper bound too and bump it only after checking that everything still works fine, as they don't seem to use semver and the API can clearly break between versions.

The same might apply to other dependencies too, maybe just ensuring to stay on the same major version, for those that uses semver.

**Comment by chocoelho** [comment]
It'll be resolved on the next release. Will close it once it's tagged and published on Pypi.
