### ISSUE TITLE
ImportError: cannot import name ScopeConsumer

### ISSUE THREAD

**Issue by chrislawlor** [PyCQA/prospector#241]
Installed prospector via `pip install prospector[with_pyroma]`

Ran at the project root, got the following stack trace:
```
Traceback (most recent call last):
  File "/Users/clawlor/.virtualenvs/pymetrics/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/prospector/run.py", line 165, in main
    prospector.execute()
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/prospector/run.py", line 53, in execute
    for tool in self.config.get_tools(found_files):
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/prospector/config/__init__.py", line 45, in get_tools
    config_result = tool.configure(self, found_files)
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 174, in configure
    self._prospector_configure(prospector_config, linter)
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 34, in _prospector_configure
    linter.load_plugin_modules(['pylint_django'])
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/pylint/lint.py", line 468, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/astroid/modutils.py", line 190, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/astroid/modutils.py", line 233, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/pylint_django/__init__.py", line 7, in <module>
    from pylint_django import plugin
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/pylint_django/plugin.py", line 3, in <module>
    from pylint_django.augmentations import apply_augmentations
  File "/Users/clawlor/.virtualenvs/pymetrics/lib/python2.7/site-packages/pylint_django/augmentations/__init__.py", line 14, in <module>
    from pylint.checkers.variables import ScopeConsumer
```

This is a Django project, running Python 2.7

**Comment by chrislawlor** [comment]
I had these pylint libs installed:
```
$ pip freeze|grep pylint
pylint==1.7.4
pylint-celery==0.3
pylint-common==0.2.5
pylint-django==0.9.0
pylint-flask==0.5
pylint-plugin-utils==0.2.6
```

Ive run `pip install -U pylint` and can now run prospector.

I'd expect pylint to have been upgraded to the minimum supported version on install.

**Comment by artemnesterenko** [comment]
Face the same issue

**Comment by rodolphopivetta** [comment]
+1

**Comment by chocoelho** [comment]
This is was an issue with [pylint-django](https://github.com/pycqa/pylint-django). Closing this issue since it belonged to another tool and seems to be fixed now.
