### ISSUE TITLE
'astroid' has no attribute 'Class'

### ISSUE THREAD

**Issue by bbettss** [PyCQA/prospector#270]
I was previously using prospector v0.12.11 and this error would happen about half the time. I upgrade prospector to the latest version and now it consistently occurs. 

```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 257, in run
    self._linter.check(self._args)
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/pylint/lint.py", line 801, in check
    self._do_check(files_or_modules)
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/pylint/lint.py", line 938, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/pylint/lint.py", line 1018, in check_astroid_module
    walker.walk(ast_node)
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/pylint/utils.py", line 1159, in walk
    self.walk(child)
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/pylint/utils.py", line 1156, in walk
    cb(astroid)
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/root/.local/share/virtualenvs/epo_model-rbZ_MJWn/lib/python3.6/site-packages/pylint_common/augmentations.py", line 23, in allow_attribute_comments
    isinstance(node.parent, (astroid.Class, astroid.Module)) and \
AttributeError: module 'astroid' has no attribute 'Class'
```

Here is the command I am using to run prospector:
`python -m pipenv run prospector --die-on-tool-error --test-warnings --doc-warnings --strictness verylow`

Below is pipenv graph and pip freeze:
```
prospector==1.0
  - dodgy [required: >=0.1.9, installed: 0.1.9]
  - mccabe [required: >=0.5.0, installed: 0.6.1]
  - pep8-naming [required: >=0.3.3, installed: 0.7.0]
    - flake8-polyfill [required: >=1.0.2,<2, installed: 1.0.2]
      - flake8 [required: Any, installed: 3.5.0]
        - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
        - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.3.1]
        - pyflakes [required: >=1.5.0,<1.7.0, installed: 1.6.0]
  - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.3.1]
  - pydocstyle [required: >=2.0.0, installed: 2.1.1]
    - six [required: Any, installed: 1.11.0]
    - snowballstemmer [required: Any, installed: 1.2.1]
  - pyflakes [required: >=0.8.1,<2.0.0, installed: 1.6.0]
  - pylint [required: >=2, installed: 2.0.1]
    - astroid [required: >=2.0.1, installed: 2.0.1]
      - lazy-object-proxy [required: Any, installed: 1.3.1]
      - six [required: Any, installed: 1.11.0]
      - typed-ast [required: Any, installed: 1.1.0]
      - wrapt [required: Any, installed: 1.10.11]
    - isort [required: >=4.2.5, installed: 4.3.4]
    - mccabe [required: Any, installed: 0.6.1]
  - pylint-common [required: >=0.2.5, installed: 0.2.5]
    - pylint [required: >=1.0, installed: 2.0.1]
      - astroid [required: >=2.0.1, installed: 2.0.1]
        - lazy-object-proxy [required: Any, installed: 1.3.1]
        - six [required: Any, installed: 1.11.0]
        - typed-ast [required: Any, installed: 1.1.0]
        - wrapt [required: Any, installed: 1.10.11]
      - isort [required: >=4.2.5, installed: 4.3.4]
      - mccabe [required: Any, installed: 0.6.1]
    - pylint-plugin-utils [required: >=0.2.5, installed: 0.4]
      - pylint [required: Any, installed: 2.0.1]
        - astroid [required: >=2.0.1, installed: 2.0.1]
          - lazy-object-proxy [required: Any, installed: 1.3.1]
          - six [required: Any, installed: 1.11.0]
          - typed-ast [required: Any, installed: 1.1.0]
          - wrapt [required: Any, installed: 1.10.11]
        - isort [required: >=4.2.5, installed: 4.3.4]
        - mccabe [required: Any, installed: 0.6.1]
  - pylint-plugin-utils [required: >=0.2.6, installed: 0.4]
    - pylint [required: Any, installed: 2.0.1]
      - astroid [required: >=2.0.1, installed: 2.0.1]
        - lazy-object-proxy [required: Any, installed: 1.3.1]
        - six [required: Any, installed: 1.11.0]
        - typed-ast [required: Any, installed: 1.1.0]
        - wrapt [required: Any, installed: 1.10.11]
      - isort [required: >=4.2.5, installed: 4.3.4]
      - mccabe [required: Any, installed: 0.6.1]
  - pyyaml [required: Any, installed: 3.13]
  - requirements-detector [required: >=0.6, installed: 0.6]
    - astroid [required: >=1.4, installed: 2.0.1]
      - lazy-object-proxy [required: Any, installed: 1.3.1]
      - six [required: Any, installed: 1.11.0]
      - typed-ast [required: Any, installed: 1.1.0]
      - wrapt [required: Any, installed: 1.10.11]
  - setoptconf [required: >=0.2.0, installed: 0.2.0]
pypandoc==1.4
  - pip [required: >=8.1.0, installed: 18.0]
  - setuptools [required: Any, installed: 40.0.0]
  - wheel [required: >=0.25.0, installed: 0.31.1]
pyspark==2.3.0
  - py4j [required: ==0.10.6, installed: 0.10.6]



astroid==2.0.1
dodgy==0.1.9
flake8==3.5.0
flake8-polyfill==1.0.2
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
numpy==1.14.2
pandas==0.22.0
pep8-naming==0.7.0
prospector==1.0
py4j==0.10.6
pycodestyle==2.3.1
pydocstyle==2.1.1
pyflakes==1.6.0
pylint==2.0.1
pylint-common==0.2.5
pylint-plugin-utils==0.4
pypandoc==1.4
pyspark==2.3.0
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.13
requirements-detector==0.6
setoptconf==0.2.0
six==1.11.0
snowballstemmer==1.2.1
typed-ast==1.1.0
wrapt==1.10.11
```

Not sure, how to fix this. Any help is much appreciated.

**Comment by ArtemBernatskyy** [comment]
But `pylint-common` is deprecated ...
