### ISSUE TITLE
"Tool pylint failed to run" with prospector 1.1

### ISSUE THREAD

**Issue by HinoReo** [PyCQA/prospector#272]
General message:
```
> prospector

Messages
========

.
  Line: None
    pylint: failure / Tool pylint failed to run (exception was raised)



Check Information
=================
         Started: 2018-07-31 10:43:42.852514
        Finished: 2018-07-31 10:43:44.120262
      Time Taken: 1.27 seconds
       Formatter: grouped
        Profiles: default, no_doc_warnings, no_test_warnings, strictness_medium, strictness_high, strictness_veryhigh, no_member_warnings
      Strictness: None
  Libraries Used: 
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 1
```

Traceback:
```
> prospector -X
Traceback (most recent call last):
  File "[venv]/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "[venv]/lib/python3.6/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "[venv]/lib/python3.6/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "[venv]/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 257, in run
    self._linter.check(self._args)
  File "[venv]/lib/python3.6/site-packages/pylint/lint.py", line 801, in check
    self._do_check(files_or_modules)
  File "[venv]/lib/python3.6/site-packages/pylint/lint.py", line 938, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "[venv]/lib/python3.6/site-packages/pylint/lint.py", line 1018, in check_astroid_module
    walker.walk(ast_node)
  File "[venv]/lib/python3.6/site-packages/pylint/utils.py", line 1159, in walk
    self.walk(child)
  File "[venv]/lib/python3.6/site-packages/pylint/utils.py", line 1156, in walk
    cb(astroid)
  File "[venv]/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "[venv]/lib/python3.6/site-packages/pylint_common/augmentations.py", line 23, in allow_attribute_comments
    isinstance(node.parent, (astroid.Class, astroid.Module)) and \
AttributeError: module 'astroid' has no attribute 'Class'
```

Version:
```
> prospector --version
prospector 1.1
```
I installed `prospector[with-everything]` via pipenv.

**Comment by HinoReo** [comment]
Note to self: look through closed issues before posting

**Comment by GregHilston** [comment]
@Spacehug Any recollection to what issue you were talking about? Looking for a solution to this and google brought me here.

**Comment by carlio** [comment]
@GregHilston this is usually caused by pylint or astroid changes that have not been backported or added to prospector's 'compat layer' - try updating things a bit to make sure you get latest of everything, there are many small fixes to deal with this kind of thing and you might solve it just with a `pip -U`.

Or not but good luck :-)

**Comment by GregHilston** [comment]
Okay, it looks like everything I have is up to date. For completion, posting versions:

```
python 3.7.3
prospector 1.1.6.4
pylint 2.3.1
```

How I call prospector

`$ prospector --profile ../prospector_profile.yaml file.py`

**Comment by GregHilston** [comment]
Downgrading to 

`pylint 2.1.1` 

worked! Hope this helps someone in the future!
