### ISSUE TITLE
Incompatible with pylint 2.2.0 ?

### ISSUE THREAD

**Issue by victornoel** [PyCQA/prospector#303]
There seems to be message ids that disappeared in pylint 2.0.0.

When I run prospector I get:
```
Traceback (most recent call last):
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/lib/python3.6/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/lib/python3.6/site-packages/prospector/run.py", line 53, in execute
    for tool in self.config.get_tools(found_files):
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/lib/python3.6/site-packages/prospector/config/__init__.py", line 41, in get_tools
    config_result = tool.configure(self, found_files)
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 189, in configure
    self._prospector_configure(prospector_config, linter)
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 66, in _prospector_configure
    'locally-enabled')  # notification about enabling a message
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/lib/python3.6/site-packages/pylint/utils.py", line 316, in disable
    msgid, enable=False, scope=scope, line=line, ignore_unknown=ignore_unknown
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/lib/python3.6/site-packages/pylint/utils.py", line 366, in _set_msg_status
    msg = self.msgs_store.get_message_definition(msgid)
  File "/home/victor/.local/share/virtualenvs/datapipe-jVSnBL5g/lib/python3.6/site-packages/pylint/utils.py", line 989, in get_message_definition
    msgid_or_symbol=msgid_or_symbol
pylint.exceptions.UnknownMessageError: No such message id locally-enabled
```

**Comment by lemcheyWhite** [comment]
Hi, noticed the same today in the morning. Looks like message id was removed in https://github.com/PyCQA/pylint/issues/2442

**Comment by carlio** [comment]
Gah, it's tricky trying to keep track of all the moving dependency parts :-)  I'll make a quick bugfix release to pin to an older pylint version then separately add a real fix for the next release to use pylint 2.2.0.

**Comment by carlio** [comment]
1.1.6.2 now released with the small hotfix to pin versions - let me know if there are any further bugs but I think this will be closed as long as you upgrade prospector.

**Comment by victornoel** [comment]
@carlio excellent, thanks!
