### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by corburn** [PyCQA/prospector#314]
```
python --version
Python 3.7.1
```

```bash
prospector --version
pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
prospector 1.1.6.2
```

```bash
prospector --output-format pylint --zero-exit --strictness veryhigh --doc-warnings --test-warnings --member-warnings --full-pep8 --with-tool pyroma --with-tool vulture --with-tool frosted --with-tool mypy
Traceback (most recent call last):
  File "bin/prospector", line 11, in <module>
    load_entry_point('prospector==1.1.6.2', 'console_scripts', 'prospector')()
  File "lib/python3.7/site-packages/prospector/run.py", line 174, in main
    prospector.print_messages()
  File "lib/python3.7/site-packages/prospector/run.py", line 134, in print_messages
    self.write_to(formatter, sys.stdout)
  File "lib/python3.7/site-packages/prospector/run.py", line 144, in write_to
    profile=self.config.show_profile
  File "lib/python3.7/site-packages/prospector/formatters/pylint.py", line 18, in render
    for message in sorted(self.messages):
  File "lib/python3.7/site-packages/prospector/message.py", line 91, in __lt__
    return self.location < other.location
  File "lib/python3.7/site-packages/prospector/message.py", line 53, in __lt__
    return (self.line or -1) < (other.line or -1)  # line can be None if it a file-global warning
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by chocoelho** [comment]
Will definitely check it, thanks for the report @corburn

**Comment by corburn** [comment]
The exception went away after I removed `--with-tool mypy`

**Comment by chocoelho** [comment]
Closing this as prospector 1.1.7 should fix this issue. Feel free to reopen it if this is erroring for you.
