### ISSUE TITLE
Not running pyling in v1.1.6.3

### ISSUE THREAD

**Issue by mpromain** [PyCQA/prospector#331]
Hi,

new release v1.1.6.3 have a bug with execute pylint.

```
.
  Line: None
    pylint: failure / Tool pylint failed to run (exception was raised)
```
```
Traceback (most recent call last):
  File "/home/mpro/.local/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/home/mpro/.local/lib/python3.6/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "/home/mpro/.local/lib/python3.6/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "/home/mpro/.local/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 256, in run
    self._linter.check(self._args)
  File "/home/mpro/.local/lib/python3.6/site-packages/pylint/lint.py", line 801, in check
    self._do_check(files_or_modules)
  File "/home/mpro/.local/lib/python3.6/site-packages/pylint/lint.py", line 938, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/mpro/.local/lib/python3.6/site-packages/pylint/lint.py", line 1018, in check_astroid_module
    walker.walk(ast_node)
  File "/home/mpro/.local/lib/python3.6/site-packages/pylint/utils.py", line 1162, in walk
    self.walk(child)
  File "/home/mpro/.local/lib/python3.6/site-packages/pylint/utils.py", line 1159, in walk
    cb(astroid)
  File "/home/mpro/.local/lib/python3.6/site-packages/pylint/checkers/variables.py", line 1360, in visit_import
    module = next(node.infer_name_module(parts[0]))
AttributeError: 'Import' object has no attribute 'infer_name_module'
```

Thanks
Martin

**Comment by mpromain** [comment]
cc @chocoelho

**Comment by chocoelho** [comment]
On it

**Comment by chocoelho** [comment]
@mpromain new version released

**Comment by dgrant** [comment]
I'm still seeing this issue... although not sure if it's the same one exactly. I'm seeing

```
Line: None
    pylint: failure / Tool pylint failed to run (exception was raised)
```

but how do I see the exception output?

**Comment by dgrant** [comment]
nvm, I found `-X`

**Comment by dgrant** [comment]
I'll file a new bug, it's different

**Comment by chocoelho** [comment]
Closing this as prospector 1.1.7 should fix this issue. Feel free to reopen it if this is erroring for you.
