### ISSUE TITLE
Disabling tools in prospector creates various errors

### ISSUE THREAD

**Issue by arnavb** [PyCQA/prospector#337]
I'm using black for autoformatting my Python code, so I decided to disable `pep8`. 

### `.prospector.yaml`

```yaml
strictness: veryhigh
autodetect: true
pep8:
  - run: false
```

### Version info

Python 3.7.1

Mac OSX 10.14 Mojave

Pipenv v2018.11.26

pyenv v1.2.9

```bash
$ prospector --version 
prospector 1.1.6.2
```

(I'm using 1.1.6.2 because of #335)

### Issue

When I run `prospector`, I get the following:

```bash
$ prospector
Traceback (most recent call last):
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/bin/prospector", line 10, in <module>
    sys.exit(main())
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/run.py", line 162, in main
    config = ProspectorConfig()
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/config/__init__.py", line 29, in __init__
    self.profile, self.strictness = self._get_profile(self.workdir, self.config)
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/config/__init__.py", line 149, in _get_profile
    profile = ProspectorProfile.load(profile_name, profile_path, forced_inherits=forced_inherits)
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 121, in load
    forced_inherits=forced_inherits or [])
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 293, in _load_and_merge
    forced_inherits=forced_inherits or [])
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 343, in _load_profile
    extra_inherits, extra_shorthands = _determine_implicit_inherits(base_contents, inherits, shorthands_found)
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 261, in _determine_implicit_inherits
    ('pep8', _determine_pep8(profile_dict)),
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 227, in _determine_pep8
    if pep8.get('full', False):
AttributeError: 'list' object has no attribute 'get'
```

I'm using pipenv, if it matters. The only other packages installed are django and black.

As for other tools, I just tested to see what would happen if tried to disable, say pylint or pyflakes. Changing the `pep8` to any of these results in a new error:

```bash
$ prospector
Traceback (most recent call last):
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/bin/prospector", line 10, in <module>
    sys.exit(main())
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/run.py", line 162, in main
    config = ProspectorConfig()
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/config/__init__.py", line 29, in __init__
    self.profile, self.strictness = self._get_profile(self.workdir, self.config)
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/config/__init__.py", line 149, in _get_profile
    profile = ProspectorProfile.load(profile_name, profile_path, forced_inherits=forced_inherits)
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 121, in load
    forced_inherits=forced_inherits or [])
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 320, in _load_and_merge
    merged = _merge_profile_dict(priority, merged)
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 209, in _merge_profile_dict
    out[key] = _merge_tool_config(value, base.get(key, {}))
  File "/Users/arnavborborah/workspace/python/django-blog-tutorial/.venv/lib/python3.7/site-packages/prospector/profiles/profile.py", line 175, in _merge_tool_config
    for key, value in priority.items():
AttributeError: 'list' object has no attribute 'items'
```

Also, on a side note, an issue template would have been nice.

**Comment by chocoelho** [comment]
@arnavb can you try:
```yaml
strictness: veryhigh
autodetect: true
pep8:
  run: false
```

**Comment by chocoelho** [comment]
Closing this as this seems mostly related to profile syntax validation. Feel free to reopen if you face this issue again.
