### ISSUE TITLE
Failing on some mypy messages

### ISSUE THREAD

**Issue by rik** [PyCQA/prospector#339]
In my project, I ran into this error:
```traceback
Traceback (most recent call last):
  File "venv/bin/prospector", line 10, in <module>
    sys.exit(main())
  File "venv/lib/python3.7/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "venv/lib/python3.7/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "venv/lib/python3.7/site-packages/prospector/tools/mypy/__init__.py", line 85, in run
    character=int(char),
ValueError: invalid literal for int() with base 10: ' note'
```
After digging a bit, I found that mypy can emit this kind of messages: `file:9: note: unused 'type: ignore' comment` and that https://github.com/PyCQA/prospector/blob/bf1930e7166012c84e730caa44fd43b3f852c876/prospector/tools/mypy/__init__.py#L79 can't handle this format.

**Comment by chocoelho** [comment]
@rik what's mypy version you're using and can you provide an example so we can test it?

**Comment by rik** [comment]
I've made [a repository](https://github.com/rik/prospector-339) to ease testing
