### ISSUE TITLE
[BUG] pyflakes crashes with python3.8 when called from prospector

### ISSUE THREAD

**Issue by vasanthn7** [PyCQA/prospector#353]
**Describe the bug**
Pyflakes crashes while running prospector. This issue was raises in pyflakes and was closed.
Issue: https://github.com/PyCQA/pyflakes/issues/367

**To Reproduce**
1. Setup venv, and activate it.
2. `pip install prospector`
3. The only python program in dir was
`import json; 
  print(json.loads("[1,2]"))`
4. Call prospector the following way 'prospector -X'
5. See error

### With a larger code base even pylint broke.
```Messages
========
.
  Line: None
    pyflakes: failure / Tool pyflakes failed to run (exception was raised)
    pylint: failure / Tool pylint failed to run (exception was raised)

Check Information
=================
         Started: 2019-11-12 11:53:48.834889
        Finished: 2019-11-12 11:55:00.227649
      Time Taken: 71.39 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, strictness_high, strictness_veryhigh, full_pep8, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, pep8, profile-validator, pyflakes, pylint
  Messages Found: 9
 External Config: pylint: /Users/tenmiles/hdp/app/.pylintrc
```

**Environment (please complete the following information):**
 - OS: macOS
 - Tool 
        pyflakes
        pylint
 - Prospector version 1.1.7
 - Python version 3.8.0

**Additional context**
- Trace back
```Traceback (most recent call last):
  File "/tmp/venv/bin/prospector", line 11, in <module>
    load_entry_point('prospector==1.1.7', 'console_scripts', 'prospector')()
  File "/private/tmp/venv/lib/python3.8/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "/private/tmp/venv/lib/python3.8/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "/private/tmp/venv/lib/python3.8/site-packages/prospector/tools/pyflakes/__init__.py", line 131, in run
    checkPath(filepath, reporter)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/api.py", line 112, in checkPath
    return check(codestr, filename, reporter)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/api.py", line 73, in check
    w = checker.Checker(tree, filename)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 494, in __init__
    self.handleChildren(tree)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 862, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/private/tmp/venv/lib/python3.8/site-packages/pyflakes/checker.py", line 696, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'CONSTANT'
```

- pip freeze
```
astroid==2.2.5
dodgy==0.1.9
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
pep8-naming==0.4.1
prospector==1.1.7
pycodestyle==2.4.0
pydocstyle==4.0.1
pyflakes==1.6.0
pylint==2.3.1
pylint-celery==0.3
pylint-django==2.0.10
pylint-flask==0.6
pylint-plugin-utils==0.6
PyYAML==5.1.2
requirements-detector==0.6
setoptconf==0.2.0
six==1.13.0
snowballstemmer==2.0.0
typed-ast==1.4.0
wrapt==1.11.2
```

**Comment by chocoelho** [comment]
Hi @vasanthn7, thanks for the report. I noticed you're using `pyflakes==1.6.0`. Is there any specific reason? You may try updating it to 2.0.0 which is the most recent version that is supported by prospector up so far.
