### ISSUE TITLE
[BUG] if ignore-path is an int, prospector fails with "AttributeError: 'int' object has no attribute 'endswith'"

### ISSUE THREAD

**Issue by BioGeek** [PyCQA/prospector#362]
**Describe the bug**
I have a [GitHub action](https://github.com/BioGeek/adventofcode/blob/master/.github/workflows/main.yml) that uses [jpetrucciani/prospector-check ](https://github.com/jpetrucciani/prospector-check ). 

It fails with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/prospector/run.py", line 162, in main
    config = ProspectorConfig()
  File "/usr/local/lib/python3.7/site-packages/prospector/config/__init__.py", line 32, in __init__
    self.ignores = self._determine_ignores(self.config, self.profile, self.libraries)
  File "/usr/local/lib/python3.7/site-packages/prospector/config/__init__.py", line 225, in _determine_ignores
    if ignore_path.endswith('/') or ignore_path.endswith('\\'):
AttributeError: 'int' object has no attribute 'endswith'

```

I have the suspicion it is because I have these lines in [my .prospector.yaml](https://github.com/BioGeek/adventofcode/blob/master/.prospector.yaml):

```
ignore-paths:
  - 2017
  - 2018

```

**To Reproduce**
1. Go to [this repository](https://github.com/BioGeek/adventofcode)
2. Go to the [Github action output page](https://github.com/BioGeek/adventofcode/runs/329293875)
3. See the error there.

**Expected behavior**
Should run prospector on the files in the 2019 directory but ignore the files in the 2017 and 2018 folders.

**Environment (please complete the following information):**
 - OS: ubuntu-18.04 in Docker environment
 - Prospector version : 1.1.7
- Python version: 3.7.4-alpine

**Comment by BioGeek** [comment]
My suspicion is conformed: if I [change](https://github.com/BioGeek/adventofcode/commit/59f2e96e9638b3ba9cb3af8d169ea193451a1baa) my .prospector.yaml to:
```

ignore-paths:
  - '2017'
  - '2018'
```

Then prospector works as intended without giving the AttributeError.
