### ISSUE TITLE
[BUG] Incompatible prospector and pylint.

### ISSUE THREAD

**Issue by Fernal73** [PyCQA/prospector#363]
https://github.com/PyCQA/pylint/issues/3270#issuecomment-561698027

Prospector is not compatible with pylint and complains about astroid version is later than version installed by pylint if pylint is installed post prospector.

```
$ pylint --version
pylint 2.4.4
astroid 2.3.3
Python 3.8.0 (default, Nov 20 2019, 20:44:46)
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6

```
Python version : 3.8-03.

Error in running prospector.

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (astroid 2.3.3 (/data/data/com.termux/files/usr/lib/python3.8/site-packages), Requirement.parse('astroid==2.2.5'), {'prospector'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/prospector", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'astroid==2.2.5' distribution was not found and is required by prospector

```

**Comment by Fernal73** [comment]
https://libraries.io/pypi/prospector

I installed prospector via:

pip install prospector==1.2.0.dev3

That works. I'll close out this issue.
