### ISSUE TITLE
[BUG] pyflakes: failure / Tool pyflakes failed to run (exception was raised)

### ISSUE THREAD

**Issue by djstein** [PyCQA/prospector#365]
Attempt to run `prospector`
output includes:
```pyflakes: failure / Tool pyflakes failed to run (exception was raised)```

Running `prospector -X` results in stack trace:
```
Traceback (most recent call last):
  File "/.venv/bin/prospector", line 8, in <module>
    sys.exit(main())
  File "/.venv/lib/python3.8/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "/.venv/lib/python3.8/site-packages/prospector/run.py", line 66, in execute
    messages += tool.run(found_files)
  File "/.venv/lib/python3.8/site-packages/prospector/tools/pyflakes/__init__.py", line 131, in run
    checkPath(filepath, reporter)
  File "/.venv/lib/python3.8/site-packages/pyflakes/api.py", line 99, in checkPath
    return check(codestr, filename, reporter)
  File "/.venv/lib/python3.8/site-packages/pyflakes/api.py", line 74, in check
    w = checker.Checker(tree, file_tokens=file_tokens, filename=filename)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 673, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 710, in runDeferred
    handler()
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1474, in runFunction
    self.handleChildren(node, omit='decorator_list')
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 1119, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/.venv/lib/python3.8/site-packages/pyflakes/checker.py", line 909, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'NAMEDEXPR'
```

**To Reproduce**
```
brew install pyenv
pyenv install 3.8.1
virtualenv .venv -p /.pyenv/versions/3.8.1/bin/python
source .venv/bin/activate # for fish shell source .venv/bin/activate.fish
pip install prospector
prospector
```

**Expected behavior**
Runs prospector and has no errors about exceptions.

**Environment (please complete the following information):**
 - OS: macOS Catalina
```
prospector 1.2.0
astroid 2.3.3
pyflakes 2.1.1
pylint                2.4.4
pylint-celery         0.3
pylint-django         2.0.12
pylint-flask          0.6
pylint-plugin-utils   0.6
```
 - Prospector version 1.2.0
- Python version 3.8.1

**Comment by djstein** [comment]
Realize this might be a `pyflakes` bug only. however, and only occurs when I have a `walrus` operator inside my source code. this results in `pyflakes` breaking.

**Comment by acnebs** [comment]
Yeah, this is from using a *pyflakes* version that doesn't support assignment expressions.

From this PR (https://github.com/PyCQA/pyflakes/pull/457), it looks like this was added in *pyflakes* `v2.2.0`, which was only released 6 days ago.

**Comment by chocoelho** [comment]
> Can we get a patch that just bumps the pyflakes version?
I should work on prospector this weekend. WFH has been very demanding, more than usual. Should have a `dev` version released this weekend and a stable by the end of the month.

**Comment by acnebs** [comment]
@chocoelho Thanks!

**Comment by chocoelho** [comment]
Hey there, just release 1.3.0.dev0. Can you check if this is still the case?

**Comment by acnebs** [comment]
Can confirm that this is no longer an issue on `1.3.0.dev1 (a4a16ab)`!
