### ISSUE TITLE
Support latest pylint, pylint-django

### ISSUE THREAD

**Issue by ajhodges** [PyCQA/prospector#393]
The latest published version of pylint is 2.5.3, and the latest pylint-django is 2.2.0.

I'm specifically interested in pylint-django 2.2.0 due to the rework of how string FK references are handled.

**Comment by djbrown** [comment]
@chocoelho any news on this?

**Comment by chocoelho** [comment]
I should tackle it in the next couple of days, as it seems the issue that blocked any advance in here for solved in pylint.

**Comment by ipaleka** [comment]
Pip brings complaints (_--use-feature=2020-resolver_ note on installing) with `Python 3.9.0`, `pylint 2.5.3` and the latest `pylint-django 2.3.0`, but everything works fine. 

But, the following is the traceback I get after installing `pylint 2.6.0`:
```
$ prospector
Traceback (most recent call last):
  File "/home/ipaleka/dev/venvs/myproject/bin/prospector", line 8, in <module>
    sys.exit(main())
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/prospector/run.py", line 167, in main
    prospector.execute()
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/prospector/run.py", line 54, in execute
    for tool in self.config.get_tools(found_files):
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/prospector/config/__init__.py", line 42, in get_tools
    config_result = tool.configure(self, found_files)
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/prospector/tools/pylint/__init__.py", line 127, in configure
    config_messages, configured_by = self._get_pylint_configuration(
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/prospector/tools/pylint/__init__.py", line 218, in _get_pylint_configuration
    config_messages = self._prospector_configure(prospector_config, linter)
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/prospector/tools/pylint/__init__.py", line 82, in _prospector_configure
    linter.disable("mixed-indentation")
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/pylint/message/message_handler_mix_in.py", line 67, in disable
    self._set_msg_status(
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/pylint/message/message_handler_mix_in.py", line 118, in _set_msg_status
    message_definitions = self.msgs_store.get_message_definitions(msgid)
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/pylint/message/message_definition_store.py", line 57, in get_message_definitions
    for m in self.message_id_store.get_active_msgids(msgid_or_symbol)
  File "/home/ipaleka/dev/venvs/myproject/lib/python3.9/site-packages/pylint/message/message_id_store.py", line 120, in get_active_msgids
    raise UnknownMessageError(error_msg)
pylint.exceptions.UnknownMessageError: No such message id or symbol 'mixed-indentation'.
```

**Comment by aidar-ms** [comment]
@chocoelho any updates on this? I think pylint-django 2.1.0 raises an error if a project uses string notation for Django FK ("app_model.Model"), which I think has been addressed in the latest versions.

**Comment by adamcunnington** [comment]
Hi, pylint supported isort 5 but I am still stuck on an outrageously old version of isort (almost 24 months old) because prospector is only supporting pylint 2.5.3. This means that I am stuck on isort 4.3 whilst 5.7 is currently stable.

What is the ETA please for prospector updating to a version of pylint that supports isort 5?
