### ISSUE TITLE
[BUG] pylint's fail with: fail-under value ('10.0') should be of type int

### ISSUE THREAD

**Issue by boatcoder** [PyCQA/prospector#396]
**Describe the bug**
Prospector won't run because of bad arguments passed to pylint

**To Reproduce**
1. Install the python package versions below and just type prospector

```
$ prospector
Traceback (most recent call last):
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/pylint/config.py", line 254, in _call_validator
    return VALIDATORS[opttype](optdict, option, value)
TypeError: int() takes at most 2 arguments (3 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/pylint/config.py", line 257, in _call_validator
    return VALIDATORS[opttype](value)
ValueError: invalid literal for int() with base 10: '10.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mark/dev/virtualenvs/elements-api/bin/prospector", line 8, in <module>
    sys.exit(main())
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/prospector/run.py", line 167, in main
    prospector.execute()
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/prospector/run.py", line 54, in execute
    for tool in self.config.get_tools(found_files):
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/prospector/config/__init__.py", line 42, in get_tools
    config_result = tool.configure(self, found_files)
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/prospector/tools/pylint/__init__.py", line 127, in configure
    config_messages, configured_by = self._get_pylint_configuration(
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/prospector/tools/pylint/__init__.py", line 214, in _get_pylint_configuration
    config_messages += self._pylintrc_configure(pylintrc, linter)
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/prospector/tools/pylint/__init__.py", line 103, in _pylintrc_configure
    are_plugins_loaded = linter.config_from_file(pylintrc)
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/prospector/tools/pylint/linter.py", line 22, in config_from_file
    self.load_config_file()
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/pylint/config.py", line 787, in load_config_file
    self.global_set_option(option, value)
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/pylint/config.py", line 668, in global_set_option
    self._all_options[opt].set_option(opt, value)
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 567, in set_option
    checkers.BaseTokenChecker.set_option(self, optname, value, action, optdict)
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/pylint/config.py", line 880, in set_option
    value = _validate(value, optdict, optname)
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/pylint/config.py", line 273, in _validate
    return _call_validator(_type, optdict, name, value)
  File "/Users/mark/dev/virtualenvs/elements-api/lib/python3.8/site-packages/pylint/config.py", line 259, in _call_validator
    raise optparse.OptionValueError(
optparse.OptionValueError: fail-under value ('10.0') should be of type int
```

**Expected behavior**
I'd like it to give me some useful information about my code rather than blowing up by passing float arguments to pylint instead of an int

**Screenshots**
Stackbacktrace is included.

**Environment (please complete the following information):**
 - OS: macOS
 - Tool pylint
 - Python 3.8.2
 - prospector==1.3.0
 - pylint==2.5.2
 - pylint-celery==0.3
 - pylint-django==2.0.15
 - pylint-flask==0.6
 - pylint-plugin-utils==0.6

**Additional context**

**Comment by chocoelho** [comment]
@boatcoder it'd be useful to know how this call took place, meaning can you attach your prospector/pylint config files?

**Comment by Thopterulu** [comment]
I just had this issue, it's when pylintrc fail-under value is set to 10.0 (default value generate with old versions of pylint)
, just change it to 10 and it will work.
So the file was generated with an older version of pylint and when you pulled prospector 1.3.0, it installed a newer version of pylint.

**Comment by abhishekvickyvyas** [comment]
I am also facing same issue

**Comment by carlio** [comment]
@abhishekvickyvyas can you post your pylint version and pylintrc file?

It sounds like this is a problem with an old pylint config file and a new pylint version, neither of which is a prospector problem.
