### ISSUE TITLE
[BUG] Pylint version cannot be found.

### ISSUE THREAD

**Issue by mdabrowski1990** [PyCQA/prospector#400]
After update of prospector and pylint, I am unable to run prospector.

# How I execute prospector
> prospector --profile prospector_profile.yaml optimization
- prospector_profile.yaml exists
- optimization is name of my project

# Traceback
```
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Python38\Scripts\prospector.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\prospector\run.py", line 167, in main
    prospector.execute()
  File "c:\python38\lib\site-packages\prospector\run.py", line 54, in execute
    for tool in self.config.get_tools(found_files):
  File "c:\python38\lib\site-packages\prospector\config\__init__.py", line 42, in get_tools
    config_result = tool.configure(self, found_files)
  File "c:\python38\lib\site-packages\prospector\tools\pylint\__init__.py", line 122, in configure
    linter = ProspectorLinter(found_files)
  File "c:\python38\lib\site-packages\prospector\tools\pylint\linter.py", line 13, in __init__
    PyLinter.__init__(self, *args, **kwargs)
  File "c:\python38\lib\site-packages\pylint\lint\pylinter.py", line 458, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'version'
```

# My setup
- Windows 10
- Python 3.8.3
[pip_freeze.txt](https://github.com/PyCQA/prospector/files/5757383/pip_freeze.txt)

**Comment by mdabrowski1990** [comment]
> 
> 
> Is this fixed in 1.4.0 ?

Yes, 1.4.0 fixes this problem.
