### ISSUE TITLE
[BUG] Vultue got an unexpected keyword argument 'exclude'

### ISSUE THREAD

**Issue by mdabrowski1990** [PyCQA/prospector#402]
I cannot run prospector with newest version of vulture.

When I try to run prospector with vulture enabled, I see the traceback:
```Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Python38\Scripts\prospector.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\prospector\run.py", line 167, in main
    prospector.execute()
  File "c:\python38\lib\site-packages\prospector\run.py", line 67, in execute
    messages += tool.run(found_files)
  File "c:\python38\lib\site-packages\prospector\tools\vulture\__init__.py", line 72, in run
    vulture = ProspectorVulture(found_files)
  File "c:\python38\lib\site-packages\prospector\tools\vulture\__init__.py", line 10, in __init__
    Vulture.__init__(self, exclude=None, verbose=False)
TypeError: __init__() got an unexpected keyword argument 'exclude'
```

To execute prospector, I use this command: ```prospector --profile prospector_profile.yaml optimization --die-on-tool-error```
where:
'prospector_profile.yaml' is my profile with vulture enabled
'optimization' is my project

These is my pip freeze: [vulture_issue_freeze.txt](https://github.com/PyCQA/prospector/files/5824125/vulture_issue_freeze.txt)
Python version: Python 3.8.3
OS: Windows10 64bit

**Comment by mdabrowski1990** [comment]
It is fixed in 1.4.0
