### ISSUE TITLE
[BUG] Vulture causing PosixPath not JSON serializable error under prospector/ALE

### ISSUE THREAD

**Issue by ristillu** [PyCQA/prospector#404]
**Describe the bug**
I'm using vulture via prospector via ALE in vim. With default ALE options prospector causes a TypeError by trying to JSON serialize the absolute path of the file causing a vulture warning. The behaviour can be reproduced at the prospector CLI.

The failing command below is the default command that is used by ALE.

There are two things required to workaround:
1. Use the vim/ALE flag `let g:ale_python_vulture_change_directory = 0` (default is `= 1`)
2. Use vulture with vim/ALE as a separate linter to prospector

**To Reproduce**
```
[user@host prospector]$ pwd
/prospector
[user@host prospector]$ cat test.py
if __name__ == '__main__':
    x = 42
    print('hello world')
[user@host prospector]$ python3 --version
Python 3.8.0
[user@host prospector]$ prospector --version
prospector 1.3.1
[user@host prospector]$ vulture --version
vulture 2.3
[user@host prospector]$ '/bin/bash' '-c' '''prospector'' --with-tool vulture --die-on-tool-error --messages-only --absolute-paths --zero-exit --output-format json ''/prospector/test.py'''
{'messages': [{'source': 'vulture', 'code': 'unused-variable', 'location': {'path': PosixPath('/prospector/test.py'), 'module': None, 'function': None, 'line': 2, 'character': None}, 'message': "Unused variable 'x'"}]}
Traceback (most recent call last):
  File "/home/ristillu/.local/bin/prospector", line 8, in <module>
    sys.exit(main())
  File "/home/ristillu/.local/lib/python3.8/site-packages/prospector/run.py", line 168, in main
    prospector.print_messages()
  File "/home/ristillu/.local/lib/python3.8/site-packages/prospector/run.py", line 128, in print_messages
    self.write_to(formatter, sys.stdout)
  File "/home/ristillu/.local/lib/python3.8/site-packages/prospector/run.py", line 136, in write_to
    formatter.render(
  File "/home/ristillu/.local/lib/python3.8/site-packages/prospector/formatters/json.py", line 36, in render
    return json.dumps(output, indent=2)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
```

**Expected behavior**
```
[user@host prospector]$ '/bin/bash' '-c' '''prospector'' --with-tool vulture --die-on-tool-error --messages-only --absolute-paths --zero-exit --output-format json ''/prospector/test.py'''
{'messages': [{'source': 'vulture', 'code': 'unused-variable', 'location': {'path': 'test.py', 'module': None, 'function': None, 'line': 2, 'character': None}, 'message': "Unused variable 'x'"}]}
{
  "messages": [
    {
      "source": "vulture",
      "code": "unused-variable",
      "location": {
        "path": "/prospector/test.py",
        "module": null,
        "function": null,
        "line": 2,
        "character": null
      },
      "message": "Unused variable 'x'"
    }
  ]
}
```
**Preferred behavior:**
To be honest I don't want my particular environment to display absolute paths anyway. I would like my combination of tools to report the relative path only. I'm using vim to flag errors and there's no room for full absolute paths + error message. I want relative path + error message only. This however is inherent to the ALE project not the prospector project and the way ALE invokes prospector. 

**Environment:**
 - OS: RHEL7
 - Tool: vim, ALE, prospector, vulture
 - Prospector version 1.3.1
 - Python version 3.8.0

**Additional context:**
This is tangential to the issue but the vim options to make it work can be something like these settings in your .vimrc:
```
" I use vim-plug for plugin management
call plug#begin('~/vim/plugged')
Plug 'dense-analysis/ale'
call plug#end()

" Up to you how you control your error list. I prefer to only open it on files I'm modifying
let g:ale_open_list = 'on_save'
let g:ale_linters = { 'python': ['prospector', 'vulture'] }
let g:ale_python_vulture_change_directory = 0
" and don't let your prospector profile enable vulture until this issue is fixed
```
If you use vim and ALE you can see the actual command ALE invokes by opening a Python file with ```:ALEInfo``` and scrolling right to the bottom.

**Comment by carlio** [comment]
Closing this issue as #408 was merged
