### ISSUE TITLE
Nested exception raised when a tool fails and raises

### ISSUE THREAD

**Issue by david-caro** [PyCQA/prospector#537]
When a tool fails and we are showing the stack trace (-X) to run and raises an exception, we are re-raising a `FatalProspectorException` but we are not setting the `message` parameter, that ends up raising a `TypeError` instead:

```
Traceback (most recent call last):
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/prospector/run.py", line 95, in execute
    messages += tool.run(found_files)
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/prospector/tools/pylint/__init__.py", line 253, in run
    self._linter.check(self._args)
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 696, in check
    ast_per_fileitem = self._get_asts(fileitems, data)
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 707, in _get_asts
    for fileitem in fileitems:
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 874, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules).values():
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/prospector/tools/pylint/linter.py", line 24, in _expand_files
    if self._files.check_module(module["path"]):
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/bin/prospector", line 8, in <module>
    sys.exit(main())
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/prospector/run.py", line 203, in main
    prospector.execute()
  File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/prospector/run.py", line 113, in execute
    raise FatalProspectorException from ex
TypeError: FatalProspectorException.__init__() missing 1 required positional argument: 'message'
```

1. Create a sate for you repo where one of the tools you are running will raise an exception (I don't know yet why the above stack trace was being raised), an example would be downloading the code in https://gerrit.wikimedia.org/r/c/operations/cookbooks/+/841089 (the above error)
2. Call prospector the following way 'prospector --profile prospector.yaml cookbooks/ -X'
3. See prospector fail with the above stack trace

**Expected behavior** Prospector should fail, but with a FatalProspectorException instead of TypeError for missing an __init__ parameter.

**Environment (please complete the following information):**

- OS: debian bookworm/sid
- Tool pylint
- Prospector version 1.7.7
- Python version 3.10.8

**Comment by david-caro** [comment]
That was fast! thanks :)
