### ISSUE TITLE
[BUG] pre-commit hook crashes when running pylint on 1.8.0

### ISSUE THREAD

**Issue by simonlindblad** [PyCQA/prospector#567]
When running prospector using pre-commit we get a failure: `AttributeError: 'FileFinder' object has no attribute 'check_module'`.

**To Reproduce** Steps to reproduce the behavior:

pre-commit config:

```
- repo: https://github.com/PyCQA/prospector
  rev: 1.8.0
  hooks:
    - id: prospector
        files: "<sub-dir-containing-python-project>"
      args:
        - "--profile=.prospector-pre-commit-config.yaml"
        - "-X"
```

The profile that's passed in:

```
pylint:
  disable:
    - import-error
pycodestyle:
  disable:
    - E501 # Pylint is checking line length for us
```

Full stack trace:

```
Traceback (most recent call last):
  File "/home/simon/.cache/pre-commit/repof2yadeoq/py_env-python3/lib/python3.10/site-packages/prospector/run.py", line 87, in execute
    messages += tool.run(found_files)
  File "/home/simon/.cache/pre-commit/repof2yadeoq/py_env-python3/lib/python3.10/site-packages/prospector/tools/pylint/__init__.py", line 239, in run
    self._linter.check(self._args)
  File "/home/simon/.cache/pre-commit/repof2yadeoq/py_env-python3/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 696, in check
    ast_per_fileitem = self._get_asts(fileitems, data)
  File "/home/simon/.cache/pre-commit/repof2yadeoq/py_env-python3/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 707, in _get_asts
    for fileitem in fileitems:
  File "/home/simon/.cache/pre-commit/repof2yadeoq/py_env-python3/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 874, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules).values():
  File "/home/simon/.cache/pre-commit/repof2yadeoq/py_env-python3/lib/python3.10/site-packages/prospector/tools/pylint/linter.py", line 29, in _expand_files
    if self._files.check_module(module):
AttributeError: 'FileFinder' object has no attribute 'check_module'
```

**Expected behavior**: No crash.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- Tool: pylint
- Prospector version 1.8.0
- Python version 3.10

I haven't seen the same when running prospector directly.

**Comment by Pierre-Sassoulas** [comment]
The last version is 1.8.3, could you try it ?

**Comment by simonlindblad** [comment]
That did the trick, thanks!
