### ISSUE TITLE
Pre-commit hook not working with rev: 1.8.4

### ISSUE THREAD

**Issue by eugene-kostrov** [PyCQA/prospector#585]
**Describe the bug** I'm trying to run the prospector using the pre-commit hook, but it doesn't work with a prospector version greater than 1.8.0 (and with 1.8.0 it kinda runs, but faces some pylint issues)

**To Reproduce** Steps to reproduce the behavior:
`.pre-commit-config.yaml`:
```
repos:
-   repo: https://github.com/PyCQA/prospector
    rev: 1.8.4
    hooks:
    -   id: prospector
        args:
        - -X
```
Call prospector the following way - ` pre-commit run --all-files`
Output:
```
[INFO] Initializing environment for https://github.com/PyCQA/prospector.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '1.8.4')
return code: 1
stdout: (none)
stderr:
    error: pathspec '1.8.4' did not match any file(s) known to git
    
Check the log at /.../.cache/pre-commit/pre-commit.log
```

<details>
<summary>pre-commit.log</summary>

### version information

```
pre-commit version: 3.0.2
git --version: git version 2.37.1 (Apple Git-137.1)
sys.version:
    3.8.15 (default, Nov 24 2022, 09:04:07) 
    [Clang 14.0.6 ]
sys.executable: /.../miniconda3/envs/environment/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '1.8.4')
return code: 1
stdout: (none)
stderr:
    error: pathspec '1.8.4' did not match any file(s) known to git
    
```

```
Traceback (most recent call last):
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/store.py", line 202, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/store.py", line 184, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/util.py", line 115, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', '1.8.4', '--depth=1')
return code: 128
stdout: (none)
stderr:
    fatal: couldn't find remote ref 1.8.4
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/commands/run.py", line 420, in run
    for hook in all_hooks(config, store)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/repository.py", line 243, in all_hooks
    return tuple(
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/repository.py", line 246, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/repository.py", line 221, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/repository.py", line 187, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/store.py", line 206, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/store.py", line 163, in _new_repo
    make_strategy(directory)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/store.py", line 204, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/store.py", line 177, in _complete_clone
    git_cmd('checkout', ref)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/.../miniconda3/envs/environment/lib/python3.8/site-packages/pre_commit/util.py", line 115, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'checkout', '1.8.4')
return code: 1
stdout: (none)
stderr:
    error: pathspec '1.8.4' did not match any file(s) known to git
```
</details>

**Expected behavior** Prospector runs all configured checks

**Environment (please complete the following information):**

- OS: macOS
- Tool [dodgy, mccabe, profile-validator, pycodestyle, pyflakes, pylint]
- Prospector version 1.8.4
- Python version 3.8.15 (via conda environment)

**Additional context** 
pre-commit 3.0.2

**Comment by carlio** [comment]
@eugene-kostrov the problem seems to be that from version 1.8.1 onward, releases were tagged as "v1.8.4" not "1.8.4"

I'm not quite sure how that got changed but that's the reason. CC @Pierre-Sassoulas 

If you change your pre-commit config to use `v1.8.4` I imagine it'd work, but we should go through and tag the versions in the previous format too.

**Comment by eugene-kostrov** [comment]
I can confirm prospector started to process the files with this fix, thank you
